ads_version: '2.0'
id: SC-002
type: schema_specification
agent: all
tier: 1
priority: critical
validates_with: AgentQMS/standards/schemas/compliance-checker.py
compliance_status: pass
memory_footprint: 90
dependencies:
- SC-001
keywords:
- artifacts
- types
- plugin system
- frontmatter
fuzzy_threshold: 0.85
description: Artifact type catalog and source-of-truth references
triggers:
  keywords:
    - artifact types
    - create artifact
    - new artifact
    - assessment
    - implementation plan
    - audit
    - design document
  patterns:
    - \bcreate\b.*\bartifact\b
    - \bnew\b.*\b(assessment|plan|audit|design)\b
  path_patterns:
    - docs/artifacts/**/*.md

artifact_type_system:
  source_of_truth: Plugin System (AgentQMS/.agentqms/plugins/artifact_types/)
  validation_schema: .agentqms/schemas/artifact_type_validation.yaml
  validation_command: cd AgentQMS/bin && make validate
  description: Plugin-based artifact types enable extensibility without code changes

artifact_types:
  allowed:
    assessment:
      plugin: AgentQMS/.agentqms/plugins/artifact_types/assessment.yaml
      location: docs/artifacts/assessments/
      purpose: Current investigations, analysis, reviews
    audit:
      plugin: AgentQMS/.agentqms/plugins/artifact_types/audit.yaml
      location: docs/artifacts/audits/
      purpose: Compliance checks, project closure audits
    bug_report:
      plugin: AgentQMS/.agentqms/plugins/artifact_types/bug_report.yaml
      location: docs/artifacts/bug_reports/
      purpose: Issue tracking, defect documentation
    design_document:
      plugin: AgentQMS/.agentqms/plugins/artifact_types/design_document.yaml
      location: docs/artifacts/design_documents/
      purpose: Specs, features, architectural designs
      frontmatter_type: design_document
      aliases:
        - design
    implementation_plan:
      plugin: AgentQMS/.agentqms/plugins/artifact_types/implementation_plan.yaml
      location: docs/artifacts/implementation_plans/
      purpose: Proposed changes, phased execution plans
    completed_plan:
      plugin: None (generated from implementation_plan)
      location: docs/artifacts/completed_plans/
      purpose: Completion reports, session summaries
    vlm_report:
      plugin: AgentQMS/.agentqms/plugins/artifact_types/vlm_report.yaml
      location: docs/artifacts/vlm_reports/
      purpose: VLM image analysis outputs
    walkthrough:
      plugin: AgentQMS/.agentqms/plugins/artifact_types/walkthrough.yaml
      location: docs/artifacts/walkthroughs/
      purpose: Step-by-step guides, verification proofs, demo documentation
  prohibited:
    - type: completion_report
      use_instead: completed_plan
    - type: report
      use_instead: completed_plan
    - type: implementation_guide
      use_instead: completed_plan
    - type: spec
      use_instead: design_document
    - type: feature
      use_instead: design_document
    - type: template
      use_instead: docs/_templates/
    - type: research
      use_instead: assessment
      reason: Research is a form of assessment (deprecated 2026-01-10)
    - type: design
      use_instead: design_document
      reason: Naming conflict resolved - use design_document (deprecated 2026-01-10)

naming_convention: YYYY-MM-DD_HHMM_{type}_{description}.md

plugin_development:
  guide: AgentQMS/docs/guides/creating-artifact-type-plugins.md
  example: AgentQMS/.agentqms/plugins/artifact_types/audit.yaml
  schema: AgentQMS/standards/schemas/plugin_artifact_type.json
