defaults:
  - train_v2
  - model/architectures/parseq
  - data/recognition
  - _self_

# Experiment Override
experiment_name: "parseq-aihub-baseline"

# Recognition-specific paths
paths:
  data_root: /workspaces/upstageailab-ocr-recsys-competition-ocr-2

# Data (recognition uses LMDB, not detection datasets)
data:
  train:
    batch_size: 192
    num_workers: 8
  val:
    batch_size: 192
    num_workers: 8

# Trainer
trainer:
  max_epochs: 20
  check_val_every_n_epoch: 1
  gradient_clip_val: 20.0

# Optimizer
optimizer:
  name: adamw
  lr: 7.0e-4
  weight_decay: 0.05

scheduler:
  name: one_cycle_lr
  max_lr: 7.0e-4
  pct_start: 0.075
  total_steps: ${trainer.max_epochs}

# Model - vocab_size from charset (1027 = 1023 chars + 4 specials: PAD/BOS/EOS/UNK)
model:
  image_size: [32, 128]
  decoder:
    params:
      vocab_size: 1027
  head:
    params:
      out_channels: 1027
