# Receipt Data Extraction Configuration
#
# This config group controls the receipt data extraction module.
# Extraction is disabled by default.

defaults:
  - _self_

extraction:
  # Enable/disable extraction module
  enabled: false

  # Extractor configuration
  extractor:
    # Minimum confidence for item extraction
    min_item_confidence: 0.5

    # Use position-based heuristics for field inference
    use_position_heuristics: true

    # Whether to extract individual line items
    extract_items: true

    # Primary language for pattern matching (ko, en)
    language: "ko"

  # Output options
  output:
    # Include raw OCR text in output
    include_raw_text: true

    # Return partial results if extraction incomplete
    allow_partial: true

    # Minimum extraction confidence to return result
    min_confidence: 0.0
