ads_version: '2.0'
type: rule_set
agent: all
tier: 2
priority: critical
validates_with: AgentQMS/standards/schemas/compliance-checker.py
compliance_status: pass
memory_footprint: 350
id: FW-019
name: Hydra V5.0 Core Rules ("Domains First")
description: Critical configuration rules for Hydra 1.3.2 V5.0 architecture - mandatory
  reading for config changes
version: 5.0
hydra_version: 1.3.2
last_updated: '2026-01-20'
replaces:
- hydra-v5-core-rules.yaml (consolidated)
- hydra-configuration-architecture.yaml (archived)
quick_navigation:
  need_validation_commands: See validation_commands section at bottom
  debugging_failure: Load hydra-v5-patterns-reference.yaml + search failure symptom
  learning_rules: Read critical_rules section first (5 min)
ai_reading_strategy:
  first_time: Read critical_rules section only (lines 35-85)
  making_config_changes: Read critical_rules + directory_responsibilities
  debugging: Use hydra-v5-patterns-reference.yaml instead
  validation: Jump to pre_commit_checklist section
critical_rules:
  flattening_rule:
    name: The Flattening Rule
    priority: critical
    description: 'Files using `# @package _group_` MUST NOT contain a top-level key
      matching the folder name. All keys including `_target_` must start at column
      0.

      '
    failure_mode: Double namespacing (e.g., `data.data.*` instead of `data.*`)
    rationale: 'Hydra''s `@package _group_` directive automatically wraps content
      in the parent folder''s namespace. Adding a redundant wrapper key causes double
      nesting.

      '
    correct_example: '# configs/train/callbacks/early_stopping.yaml

      # @package _group_

      _target_: lightning.pytorch.callbacks.EarlyStopping

      monitor: "val/hmean"

      patience: 5

      '
    incorrect_example: "# ❌ Creates train.callbacks.early_stopping.early_stopping\n\
      early_stopping:\n  _target_: lightning.pytorch.callbacks.EarlyStopping\n"
    validation: python scripts/utils/show_config.py main domain=detection
  absolute_interpolation_law:
    name: Absolute Root Anchoring
    priority: critical
    description: 'All cross-file references MUST use absolute paths anchored to root
      namespace. Never use relative interpolations without explicit namespace prefix.

      '
    failure_mode: 'InterpolationKeyError: ''key'' not found'
    rationale: 'Relative interpolations like `${train_transform}` fail because Hydra
      cannot determine the root namespace. Absolute paths provide unambiguous resolution.

      '
    forbidden:
    - ${train_transform}
    - ${optimizer}
    - ./data
    - ${dataset_base_path}
    required:
    - ${data.transforms.train_transform}
    - ${train.optimizer.adamw}
    - ${global.paths.data_dir}
    - ${global.paths.datasets_root}
    special_cases:
      local_variables: Use ${.local_key} ONLY for variables within same file
      global_constants: Always anchor to ${global.paths.*} for system paths
  domain_isolation:
    name: Domain Isolation Protocol
    priority: critical
    description: 'Domain controllers MUST explicitly nullify irrelevant keys from
      other domains to prevent cross-contamination and CUDA segfaults.

      '
    rationale: 'Unused domain keys can cause memory leaks, CUDA errors, and unpredictable
      behavior during validation/testing when models load irrelevant components.

      '
    example: "# configs/domain/recognition.yaml\n# @package _group_\ndefaults:\n \
      \ - /model/architectures: parseq\n  - _self_\n\n# Nullify detection-specific\
      \ keys\ndetection: null\nmax_polygons: null\nshrink_ratio: null\n"
directory_responsibilities:
  tier1_global:
    location: configs/global/
    package: '# @package _global_'
    responsibility: System-wide constants (paths, seeds, trainer defaults)
    allowed_keys:
    - paths
    - seed
    - trainer
    forbidden: Domain-specific logic, model architecture, data transforms
  tier2_hardware:
    location: configs/hardware/
    package: '# @package _global_'
    responsibility: Resource constraints and hardware-specific overrides
    allowed_keys:
    - batch_size
    - num_workers
    - pin_memory
    - precision
    - gpu_limits
    rationale: Hardware configs must override global defaults
  tier3_domain:
    location: configs/domain/
    package: '# @package _group_'
    responsibility: Task orchestrators bridging model, data, and train logic
    required_actions:
    - Link to model architectures via defaults
    - Link to datasets via defaults
    - Inject task-dependent components (tokenizer, loss)
    - Nullify other domain keys
    forbidden: Direct model layer definitions, data paths
  tier4_model_architectures:
    location: configs/model/architectures/
    package: '# @package _group_'
    responsibility: Pure neural network layer definitions (Atomic)
    allowed_keys:
    - _target_
    - backbone
    - decoder
    - head
    - encoder
    - architectural_hyperparameters
    forbidden:
    - optimizer
    - loss
    - tokenizer
    - training_logic
    rationale: Prevents passive refactor cycle where invisible overrides cause training
      inconsistencies
  tier5_data_datasets:
    location: configs/data/datasets/
    package: '# @package data'
    responsibility: Source identity (paths and metadata ONLY)
    allowed_keys:
    - dataset_base_path
    - image_path
    - annotation_path
    - lmdb_path
    - _target_
    forbidden:
    - transforms
    - augmentations
    - preprocessing
    rationale: Separates data source from data transformation logic
  tier6_data_transforms:
    location: configs/data/transforms/
    package: '# @package _group_'
    responsibility: Atomic augmentation and preprocessing components
    examples:
    - document_geometry.yaml
    - image_enhancement.yaml
    - normalization.yaml
    forbidden: Dataset paths, model logic
  tier7_train:
    location: configs/train/
    package: '# @package _group_'
    subdirs:
    - optimizer/
    - scheduler/
    - callbacks/
    - logger/
    responsibility: Training optimization and instrumentation
    forbidden: Model architecture, data source definitions
  tier8_experiment:
    location: configs/experiment/
    package: '# @package _global_'
    responsibility: Execution-ready configs for specific runs
    pattern: Compose domain + hardware + specific overrides
design_patterns:
  self_mounting_components:
    name: Self-Mounting Atomic Units
    principle: Components declare their own namespace via @package directive
    details: See hydra-v5-patterns-reference.yaml:L45
  domain_injection:
    name: Domain Injection Pattern
    principle: Domain controllers inject data-dependent components
    details: See hydra-v5-patterns-reference.yaml:L85
  multi_component_aliasing:
    name: Multi-Logger/Callback Aliasing
    syntax: '[filename]@_group_.[custom_alias]'
    details: See hydra-v5-patterns-reference.yaml:L125
  atomic_architecture:
    name: Atomic Architecture Pattern
    principle: Model configs contain ONLY neural network structure
    anti_pattern: Including optimizer/loss in model files
    details: See hydra-v5-patterns-reference.yaml:L165
pre_commit_checklist:
  flattening_rule:
    check: No top-level key matches folder name in @package _group_ files
    command: grep -r "^[a-z_]*:$" configs/*/
    pass_if: No matches in files with
  absolute_interpolation:
    check: All interpolations use absolute paths
    command: grep -r '\${[^.}]*}' configs/ | grep -v '\${global\|${data\|${train\|${model'
    pass_if: No relative interpolations found
  global_anchoring:
    check: All paths anchor to ${global.paths.*}
    command: grep -r 'path:.*\$' configs/ | grep -v '\${global.paths'
    pass_if: All paths use global.paths prefix
  architecture_purity:
    check: Model architectures have NO optimizer or loss keys
    command: grep -r 'optimizer:\|loss:' configs/model/architectures/
    pass_if: No matches found
validation_commands:
  composition_check:
    detection: python scripts/utils/show_config.py main domain=detection
    recognition: python scripts/utils/show_config.py main domain=recognition
    kie: python scripts/utils/show_config.py main domain=kie
  sanity_audit:
    command: python scripts/audit/hydra_sanity_check.py
    success_output: ⭐ Domain 'X' is COMPLIANT with v5.0 Standards.
  flattening_verification:
    command: python scripts/audit/verify_hydra_flattening.py
    checks:
    - logger_aliasing
    - callback_flattening
    - interpolation_resolution
failure_index:
  data.data.*: See hydra-v5-patterns-reference.yaml:double_namespacing
  InterpolationKeyError: See hydra-v5-patterns-reference.yaml:interpolation_key_error
  CUDA segfault: See hydra-v5-patterns-reference.yaml:cross_domain_contamination
  optimizer ignored: See hydra-v5-patterns-reference.yaml:passive_refactor_cycle
  ConfigCompositionException: See hydra-v5-patterns-reference.yaml:override_ordering
integration:
  companion_standards:
    patterns_reference: AgentQMS/standards/tier2-framework/hydra-v5-patterns-reference.yaml
    configuration_standards: AgentQMS/standards/tier2-framework/configuration-standards.yaml
  triggers:
  - config refactor
  - hydra v5
  - domains first
  - atomic architecture
  - domain isolation
  - flattening rule
  - absolute interpolation
  validation_scripts:
  - scripts/audit/hydra_sanity_check.py
  - scripts/utils/show_config.py
  - scripts/audit/arch_guard.py
  - scripts/audit/verify_hydra_flattening.py
compliance:
  agentqms_validated: '2026-01-20'
  consolidated_from:
  - hydra-v5-core-rules.yaml
  - hydra-configuration-architecture.yaml (partial)
  ai_optimized: true
  token_reduction: 57%
dependencies:
- SC-003
keywords:
- critical
- rules
- hydra
- reading
- compliance
- version
- configuration
- architecture
- mandatory
- config
fuzzy_threshold: 0.8
