# @package _global_

# Text Detection Domain Configuration
# Use with: python runners/train.py +domain=detection

defaults:
  - override /model/architectures: dbnet
  - override /data: canonical
  - _self_

task: detection
batch_size: 16
skip_test: true

model:
  type: detection
  task_type: detection

data:
  task_type: detection
