ads_version: '2.0'
id: FW-039
type: rule_set
agent: all
tier: 2
priority: high
validates_with: AgentQMS/standards/schemas/compliance-checker.py
compliance_status: unknown
memory_footprint: 40
keywords:
- discovery
- triggers
- workflow
- experiment_manager
fuzzy_threshold: 0.8
description: Discovery triggers mapping file patterns to experiment workflow actions
triggers:
- pattern: ocr/models/**/*.py
  workflow: check.validate
- pattern: configs/**/*.yaml
  workflow: check.validate
- pattern: experiment_manager/**/*.py
  workflow: database.reconcile
