ads_version: '2.0'
id: SC-001
type: rule_set
agent: all
tier: 1
priority: critical
validates_with: AgentQMS/standards/schemas/compliance-checker.py
compliance_status: pass
memory_footprint: 80
dependencies: []
keywords:
  - naming
  - kebab-case
  - artifacts
  - conventions
  - file naming
  - timestamp
fuzzy_threshold: 0.85
description: File and artifact naming conventions for the project
triggers:
  keywords:
    - naming conventions
    - file naming
    - artifact naming
    - kebab-case
    - timestamp format
  patterns:
    - \bnaming\b.*\bconvention
    - \bfile\b.*\bname
    - \bartifact\b.*\bname
  path_patterns:
    - docs/artifacts/**/*.md

naming_rules:
  artifact_format:
    pattern: YYYY-MM-DD_HHMM_{TYPE}_descriptive-slug.md
    enforcement: pre-commit hook
    violations:
      - ALL-CAPS filenames (except README.md, CHANGELOG.md)
      - Missing timestamp prefix
      - Underscores in slug portion
  artifact_type_prefixes:
    implementation_plan: implementation_plan_
    assessment: assessment_
    audit: audit_
    design_document: design_document_
    research: research_
    template: template_
    bug_report: bug_
    session_note: SESSION_
  case_rules:
    allowed: lowercase-with-hyphens (kebab-case)
    prohibited:
      - ALL_CAPS_NAMES
      - camelCase
      - PascalCase
      - snake_case in slug
  timestamp_format:
    file: YYYY-MM-DD_HHMM
    frontmatter_date: YYYY-MM-DD HH:MM (KST)
    example_file: 2025-12-16_1915_assessment_example.md
    example_frontmatter: 2025-12-16 19:15 (KST)

validation_command: make validate
enforcement_mechanism: AgentQMS artifact_workflow.py + pre-commit hooks
