# Text Recognition Configuration
#
# This config group controls the text recognition module.
# Recognition is disabled by default and must be explicitly enabled.

defaults:
  - _self_

recognition:
  # Enable/disable recognition module
  enabled: false

  # Recognition backend: stub | trocr | crnn | paddleocr
  # - stub: Placeholder returning dummy text (for testing)
  # - trocr: Microsoft TrOCR transformer-based recognizer
  # - crnn: CNN+RNN architecture
  # - paddleocr: PaddlePaddle OCR recognizer
  backend: "stub"

  # Path to recognition model checkpoint (null for stub backend)
  model_path: null

  # Maximum batch size for recognition inference
  max_batch_size: 32

  # Target height for normalized text crops (pixels)
  target_height: 32

  # Target language code (e.g., "ko", "en", "zh")
  language: "ko"

  # Device for inference ("cuda" or "cpu", auto-detected if null)
  device: null

# Crop extraction settings
crop_extraction:
  # Minimum width for valid crops (pixels)
  min_width: 8

  # Maximum width/height aspect ratio
  max_aspect_ratio: 25.0

  # Padding ratio around detected region (0.0-0.5)
  padding_ratio: 0.1

  # Enable perspective correction for 4-point polygons
  enable_perspective_correction: true
