---
ads_version: "1.0"
type: workflow_definition
agent: all
tier: 4
priority: high
validates_with: "AgentQMS/standards/schemas/compliance-checker.py"
compliance_status: unknown
memory_footprint: 200
date: "2025-12-27"
status: active

# Experiment Workflow Reference
# Location: experiment_manager/
# Agent Interface: experiment_manager/agent_interface.yaml (Primary Source of Truth)

workflow:
  start:
    command: "uv run python experiment_manager/etk.py init {name}"
    result: "Creates experiments/YYYYMMDD_HHMMSS_{name}/ with strict schema structure."

  create_artifact:
    assessment: "uv run python experiment_manager/etk.py create assessment '{title}'"
    report: "uv run python experiment_manager/etk.py create report '{title}' --metrics 'acc,f1'"
    guide: "uv run python experiment_manager/etk.py create guide '{title}'"
    script: "uv run python experiment_manager/etk.py create script '{title}'"

  context_tracking:
    add_task: "uv run python experiment_manager/scripts/add-task.py '{description}'"
    complete_task: "uv run python experiment_manager/scripts/complete-task.py {task_id}"
    log_insight: "uv run python experiment_manager/scripts/log-insight.py '{insight}'"

  check:
    status: "uv run python experiment_manager/etk.py status"
    list: "uv run python experiment_manager/etk.py list"
    validate: "uv run python experiment_manager/etk.py validate --all"

  database:
    reconcile: "uv run python experiment_manager/etk.py reconcile --all"
    sync: "uv run python experiment_manager/etk.py sync --all"

paths:
  module: "experiment_manager/"
  experiments: "experiment_manager/experiments/"
  agent_interface: "experiment_manager/agent_interface.yaml"

triggers:
  - pattern: "ocr/models/**/*.py"
    workflow: "check.validate"
  - pattern: "configs/**/*.yaml"
    workflow: "check.validate"
  - pattern: "experiment_manager/**/*.py"
    workflow: "database.reconcile"

rules:
  - Read experiment_manager/agent_interface.yaml for exact command arguments.
  - Always run "etk reconcile --all" and "etk sync --all" after creating artifacts.
  - Never create artifacts manually.
