# @package model

defaults:
  - architectures: dbnet
  - optimizers: adam
  - _self_

_target_: ocr.core.models.architecture.OCRModel

# Optional component overrides applied on top of architecture presets.
component_overrides: {}

# Optional learning rate scheduler configuration populated by presets or UI overrides.
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 1000
  eta_min: 0
