# @package model

defaults:
  - architectures: parseq
  - optimizers: adam
  - _self_

_target_: ocr.core.models.architecture.OCRModel

# Optional component overrides
component_overrides: {}

# Optional learning rate scheduler
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 1000
  eta_min: 0
